city_selector_task:
  description: >
    Using the customer preferences provided in your role, conduct thorough research to recommend the top 5 travel destinations for a holiday.
    For each destination, include a detailed explanation of how it meets the customer's criteria.
    Ensure the reasoning clearly maps to the preferences described in your prompt.
    
    Customer Preferences:
    - **Weather:** {weather}
    - **Country:** {country}
    - **Interested in Beaches:** {beaches}
    - **Interested in Mountains:** {mountains}
    - **Interested in exploring new cultures:** {new_cultures}
    - **Interested in Architectures:** {architectures}
    - **Interested in Pubs and Bars and nightlife:** {nightlife}
    - **Interested in exploring Nature in its raw form:** {nature}
    - **Travelling with kids:** {kids}
    - **Number of Days:** {duration}
  expected_output: >
    A list of the top recommended destination with detailed justifications for each choice, specifying how they fulfill the given preferences.
  agent: city_selector


recommend_local_experiences_task:
  description: >
    Based on the visitor's preferences, provide a list of the top 5 unique local experiences in the city. 
    For each experience, explain why it is worth visiting and how it aligns with the visitor's interests.
    Highlight aspects like food, culture, hidden spots, and popular attractions as applicable.
  expected_output: >
    A list of 5 local experiences with detailed descriptions and reasons for recommending each, tailored to the visitor's preferences.
  inputs:
    - Visitor preferences: {preferences}
    - Travel style: {travel_style}
    - Interests: {interests}
  agent: local_guide


create_travel_itinerary_task:
  description: >
    Create a comprehensive travel itinerary for the visitor based on their preferences, available time, and interests. 
    The itinerary should include daily schedules with recommended activities, places to visit, dining options, and rest periods. 
    Ensure the itinerary is efficient, enjoyable, and realistic, accounting for travel time and flexibility.
  expected_output: >
    A detailed itinerary broken down by day, including activities, destinations, dining recommendations, and notes on transportation and timing.
  inputs:
    - Trip duration: {duration}
    - Visitor preferences: {preferences}
    - Travel style: {travel_style}
    - Interests: {interests}
  agent: itinerarie_maker

report_city_name:
  description: >
    Gather Statistics
  expected_output: >
    Just specify the name of city and trip duration in days and average temperature in celcius of this city in december month
    
    Example:
    city: Pilani
    duration_in_days: 5
    average_temp_in_decemeber(in Celcius): 8
  agent: itinerarie_maker
