risk_analysis_task:
  description: >
    Analyze the given stock data and assign a **Risk Score (0-100)** based on 
    volatility (Beta), debt-to-equity ratio, market capitalization, and financial stability.  
    Lower scores indicate safer investments.  
    Provide **key observations** explaining why each stock received its score.
    ---
    Stocks to analyze: {Stock_Symbols}  
  expected_output: >
    A structured risk report including:  
    - {Stock Symbol}: Risk Score = {Value}/100  
    - Key Observations: {Brief explanation of the score}  
  agent: risk_analyst

sentiment_analysis_task:
  description: >
    Evaluate **recent financial news sentiment** for each stock based on the given data.  
    Classify the sentiment as **Positive, Neutral, or Negative** and highlight 
    any major concerns affecting the stock's perception in the market.  
  input: stock name such as INFY
  expected_output: >
    A sentiment report including:  
    - {Stock Symbol}: Sentiment = {Positive/Neutral/Negative}  
    - Key Observations: {Brief explanation of sentiment trends}  
  agent: market_sentiment_analyst

investment_recommendation_task:
  description: >
    Generate a stock recommendation list tailored to the user's **risk appetite**.  
    Only suggest stocks that align with the investor's preferred risk level.  
    Provide clear reasoning for each recommendation, including financial fundamentals,  
    sentiment trends, and potential risks.  
  expected_output: >
    A structured list of **recommended stocks**, including:  
    - ✅ {Stock Name} ({Stock Symbol})  
      - **Price:** ₹{Value}  
      - **P/E Ratio:** {Value}  
      - **Market Cap:** {Large / Mid / Small}  
      - **Risk Score:** {Value}/100  
      - **Sentiment:** {Positive / Neutral / Negative}  
      - **Why it's recommended:** {Reasoning based on risk and valuation}  
      - **Potential risks:** {If any}  
  agent: investment_advisor
